classDiagram
    class Animal {
        +name: string
        +age: int
        +makeSound(): void
    }


    class Pessoa {
        +name: string
        -age: int
        +makeSound(): void
    }

Animal --> Pessoa : Pertence